# Generated by Django 5.2.14 on 2026-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('want', 'Want to Try'), ('visited', 'Visited')], default='want', max_length=20),
        ),
    ]
