# Generated by Django 5.2.14 on 2026-05-06 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_restaurant_status_userrestaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
